### ISSUE TITLE
Problema no start do projeto

### ISSUE THREAD

**Issue by gabrielgodoy** [paulocsanz/mini-bank#1]
Fala cara, 
Sou da Stone e fiquei encarregado de avaliar o seu projeto.

Porém, estou com um problema para fazer o login:

![image](https://user-images.githubusercontent.com/2944970/34446454-3c6b8102-ecc2-11e7-8b39-35a2109b8e79.png)

Sabe o que pode ser?

---

Eu configurei o arquivo src/config.rs com todas as variáveis:

![image](https://user-images.githubusercontent.com/2944970/34446460-4e4b5924-ecc2-11e7-8a51-9c10e6dea1e5.png)

---

Essa seção está com uma orientação um pouco vaga:

![image](https://user-images.githubusercontent.com/2944970/34446493-96df8a98-ecc2-11e7-99b3-0502f181252a.png)

Abraços!

**Comment by paulocsanz** [comment]
Boa noite Gabriel, não entro muito no github no dia a dia ainda mais nesse período e acabei não vendo essa Issue, desculpe pela demora.

Não consegui replicar o problema, o que acontece exatamente? Aqui tanto o cadastro quanto a autenticação funcionam com essas configurações. Se tiver como descrever os eventos até o problema,  um backtrace se causar um panic, ou o que está acontecendo.

E há alguns problemas na configuração, o EMAIL_RECEIVER é necessário para receber o e-mail de criação de contas e o EMAIL_HOST é o endereço de SMTP do servidor, que para o gmail é **smtp.gmail.com**. Mas eles não atrapalham a autenticação.

**Comment by gabrielgodoy** [comment]
Fala cara, eu recebo essa tela quando tento autenticar:

![image](https://user-images.githubusercontent.com/2944970/35593176-524d1326-05f6-11e8-9f13-bc68d5e400cc.png)

Mesmo colocando os dados corretos no arquivo `src/config.rs` :

```
// Account used to send e-mails
env::set_var("EMAIL_USERNAME", "ggodoyoliveira@gmail.com");
env::set_var("EMAIL_PASSWORD", "12345");
```


Onde eu defino as variáveis pra fazer login, `email` e `password`?

**Comment by paulocsanz** [comment]
Boa noite, você se cadastrou, na página de Sign-up? Porque ao cadastrar você já é autenticado e nas próximas vezes basta utilizar essa conta no Sign-in.

**Comment by gabrielgodoy** [comment]
Agora foi.

Quando o sistema levanta na porta `3000` é a página de sign-in que abre. 

Portanto só depois que você me disse, que eu fiquei sabendo que teria de ir até a página de sign-up.

Seria legal colocar esse tipo de orientação na documentação de start.
